/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    UMask: typeof import('uview-pro/components/u-mask/u-mask.vue')['default']
    UPopup: typeof import('uview-pro/components/u-popup/u-popup.vue')['default']
    USelect: typeof import('uview-pro/components/u-select/u-select.vue')['default']
    USwiper: typeof import('uview-pro/components/u-swiper/u-swiper.vue')['default']
  }
}
